name: Push to VPS
on: [push]
jobs:
  deploy:
    runs-on: [debian-latest]
    steps:
      - uses: actions/checkout@v1
      - name: Push to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_SSH_USERNAME }}
          password: ${{ secrets.VPS_SSH_PASSWORD }}
          script: cd ${{ secrets.CBOT_PATH }} && git pull
